import { Chapter } from '@/types'

export const CHAPTERS: Chapter[] = [
  {
    id: 1,
    name: 'الفاتحة',
    type: 'Meccan',
    verseCount: 7,
    translation: 'The Opener',
    transliteration: 'Al-Fatihah',
  },
  {
    id: 2,
    name: 'البقرة',
    type: 'Medinan',
    verseCount: 286,
    translation: 'The Cow',
    transliteration: 'Al-Baqarah',
  },
  {
    id: 3,
    name: 'آل عمران',
    type: 'Medinan',
    verseCount: 200,
    translation: 'Family of Imran',
    transliteration: "Ali 'Imran",
  },
  {
    id: 4,
    name: 'النساء',
    type: 'Medinan',
    verseCount: 176,
    translation: 'The Women',
    transliteration: 'An-Nisa',
  },
  {
    id: 5,
    name: 'المائدة',
    type: 'Medinan',
    verseCount: 120,
    translation: 'The Table Spread',
    transliteration: "Al-Ma'idah",
  },
  {
    id: 6,
    name: 'الأنعام',
    type: 'Meccan',
    verseCount: 165,
    translation: 'The Cattle',
    transliteration: "Al-An'am",
  },
  {
    id: 7,
    name: 'الأعراف',
    type: 'Meccan',
    verseCount: 206,
    translation: 'The Heights',
    transliteration: "Al-A'raf",
  },
  {
    id: 8,
    name: 'الأنفال',
    type: 'Medinan',
    verseCount: 75,
    translation: 'The Spoils of War',
    transliteration: 'Al-Anfal',
  },
  {
    id: 9,
    name: 'التوبة',
    type: 'Medinan',
    verseCount: 129,
    translation: 'The Repentance',
    transliteration: 'At-Tawbah',
  },
  {
    id: 10,
    name: 'يونس',
    type: 'Meccan',
    verseCount: 109,
    translation: 'Jonah',
    transliteration: 'Yunus',
  },
  {
    id: 11,
    name: 'هود',
    type: 'Meccan',
    verseCount: 123,
    translation: 'Hud',
    transliteration: 'Hud',
  },
  {
    id: 12,
    name: 'يوسف',
    type: 'Meccan',
    verseCount: 111,
    translation: 'Joseph',
    transliteration: 'Yusuf',
  },
  {
    id: 13,
    name: 'الرعد',
    type: 'Medinan',
    verseCount: 43,
    translation: 'The Thunder',
    transliteration: "Ar-Ra'd",
  },
  {
    id: 14,
    name: 'ابراهيم',
    type: 'Meccan',
    verseCount: 52,
    translation: 'Abraham',
    transliteration: 'Ibrahim',
  },
  {
    id: 15,
    name: 'الحجر',
    type: 'Meccan',
    verseCount: 99,
    translation: 'The Rocky Tract',
    transliteration: 'Al-Hijr',
  },
  {
    id: 16,
    name: 'النحل',
    type: 'Meccan',
    verseCount: 128,
    translation: 'The Bee',
    transliteration: 'An-Nahl',
  },
  {
    id: 17,
    name: 'الإسراء',
    type: 'Meccan',
    verseCount: 111,
    translation: 'The Night Journey',
    transliteration: 'Al-Isra',
  },
  {
    id: 18,
    name: 'الكهف',
    type: 'Meccan',
    verseCount: 110,
    translation: 'The Cave',
    transliteration: 'Al-Kahf',
  },
  {
    id: 19,
    name: 'مريم',
    type: 'Meccan',
    verseCount: 98,
    translation: 'Mary',
    transliteration: 'Maryam',
  },
  {
    id: 20,
    name: 'طه',
    type: 'Meccan',
    verseCount: 135,
    translation: 'Ta-Ha',
    transliteration: 'Taha',
  },
  {
    id: 21,
    name: 'الأنبياء',
    type: 'Meccan',
    verseCount: 112,
    translation: 'The Prophets',
    transliteration: 'Al-Anbya',
  },
  {
    id: 22,
    name: 'الحج',
    type: 'Medinan',
    verseCount: 78,
    translation: 'The Pilgrimage',
    transliteration: 'Al-Hajj',
  },
  {
    id: 23,
    name: 'المؤمنون',
    type: 'Meccan',
    verseCount: 118,
    translation: 'The Believers',
    transliteration: "Al-Mu'minun",
  },
  {
    id: 24,
    name: 'النور',
    type: 'Medinan',
    verseCount: 64,
    translation: 'The Light',
    transliteration: 'An-Nur',
  },
  {
    id: 25,
    name: 'الفرقان',
    type: 'Meccan',
    verseCount: 77,
    translation: 'The Criterion',
    transliteration: 'Al-Furqan',
  },
  {
    id: 26,
    name: 'الشعراء',
    type: 'Meccan',
    verseCount: 227,
    translation: 'The Poets',
    transliteration: "Ash-Shu'ara",
  },
  {
    id: 27,
    name: 'النمل',
    type: 'Meccan',
    verseCount: 93,
    translation: 'The Ant',
    transliteration: 'An-Naml',
  },
  {
    id: 28,
    name: 'القصص',
    type: 'Meccan',
    verseCount: 88,
    translation: 'The Stories',
    transliteration: 'Al-Qasas',
  },
  {
    id: 29,
    name: 'العنكبوت',
    type: 'Meccan',
    verseCount: 69,
    translation: 'The Spider',
    transliteration: "Al-'Ankabut",
  },
  {
    id: 30,
    name: 'الروم',
    type: 'Meccan',
    verseCount: 60,
    translation: 'The Romans',
    transliteration: 'Ar-Rum',
  },
  {
    id: 31,
    name: 'لقمان',
    type: 'Meccan',
    verseCount: 34,
    translation: 'Luqman',
    transliteration: 'Luqman',
  },
  {
    id: 32,
    name: 'السجدة',
    type: 'Meccan',
    verseCount: 30,
    translation: 'The Prostration',
    transliteration: 'As-Sajdah',
  },
  {
    id: 33,
    name: 'الأحزاب',
    type: 'Medinan',
    verseCount: 73,
    translation: 'The Combined Forces',
    transliteration: 'Al-Ahzab',
  },
  {
    id: 34,
    name: 'سبإ',
    type: 'Meccan',
    verseCount: 54,
    translation: 'Sheba',
    transliteration: 'Saba',
  },
  {
    id: 35,
    name: 'فاطر',
    type: 'Meccan',
    verseCount: 45,
    translation: 'Originator',
    transliteration: 'Fatir',
  },
  {
    id: 36,
    name: 'يس',
    type: 'Meccan',
    verseCount: 83,
    translation: 'Ya Sin',
    transliteration: 'Ya-Sin',
  },
  {
    id: 37,
    name: 'الصافات',
    type: 'Meccan',
    verseCount: 182,
    translation: 'Those who set the Ranks',
    transliteration: 'As-Saffat',
  },
  {
    id: 38,
    name: 'ص',
    type: 'Meccan',
    verseCount: 88,
    translation: 'The Letter "Saad"',
    transliteration: 'Sad',
  },
  {
    id: 39,
    name: 'الزمر',
    type: 'Meccan',
    verseCount: 75,
    translation: 'The Troops',
    transliteration: 'Az-Zumar',
  },
  {
    id: 40,
    name: 'غافر',
    type: 'Meccan',
    verseCount: 85,
    translation: 'The Forgiver',
    transliteration: 'Ghafir',
  },
  {
    id: 41,
    name: 'فصلت',
    type: 'Meccan',
    verseCount: 54,
    translation: 'Explained in Detail',
    transliteration: 'Fussilat',
  },
  {
    id: 42,
    name: 'الشورى',
    type: 'Meccan',
    verseCount: 53,
    translation: 'The Consultation',
    transliteration: 'Ash-Shuraa',
  },
  {
    id: 43,
    name: 'الزخرف',
    type: 'Meccan',
    verseCount: 89,
    translation: 'The Ornaments of Gold',
    transliteration: 'Az-Zukhruf',
  },
  {
    id: 44,
    name: 'الدخان',
    type: 'Meccan',
    verseCount: 59,
    translation: 'The Smoke',
    transliteration: 'Ad-Dukhan',
  },
  {
    id: 45,
    name: 'الجاثية',
    type: 'Meccan',
    verseCount: 37,
    translation: 'The Crouching',
    transliteration: 'Al-Jathiyah',
  },
  {
    id: 46,
    name: 'الأحقاف',
    type: 'Meccan',
    verseCount: 35,
    translation: 'The Wind-Curved Sandhills',
    transliteration: 'Al-Ahqaf',
  },
  {
    id: 47,
    name: 'محمد',
    type: 'Medinan',
    verseCount: 38,
    translation: 'Muhammad',
    transliteration: 'Muhammad',
  },
  {
    id: 48,
    name: 'الفتح',
    type: 'Medinan',
    verseCount: 29,
    translation: 'The Victory',
    transliteration: 'Al-Fath',
  },
  {
    id: 49,
    name: 'الحجرات',
    type: 'Medinan',
    verseCount: 18,
    translation: 'The Rooms',
    transliteration: 'Al-Hujurat',
  },
  {
    id: 50,
    name: 'ق',
    type: 'Meccan',
    verseCount: 45,
    translation: 'The Letter "Qaf"',
    transliteration: 'Qaf',
  },
  {
    id: 51,
    name: 'الذاريات',
    type: 'Meccan',
    verseCount: 60,
    translation: 'The Winnowing Winds',
    transliteration: 'Adh-Dhariyat',
  },
  {
    id: 52,
    name: 'الطور',
    type: 'Meccan',
    verseCount: 49,
    translation: 'The Mount',
    transliteration: 'At-Tur',
  },
  {
    id: 53,
    name: 'النجم',
    type: 'Meccan',
    verseCount: 62,
    translation: 'The Star',
    transliteration: 'An-Najm',
  },
  {
    id: 54,
    name: 'القمر',
    type: 'Meccan',
    verseCount: 55,
    translation: 'The Moon',
    transliteration: 'Al-Qamar',
  },
  {
    id: 55,
    name: 'الرحمن',
    type: 'Medinan',
    verseCount: 78,
    translation: 'The Beneficent',
    transliteration: 'Ar-Rahman',
  },
  {
    id: 56,
    name: 'الواقعة',
    type: 'Meccan',
    verseCount: 96,
    translation: 'The Inevitable',
    transliteration: "Al-Waqi'ah",
  },
  {
    id: 57,
    name: 'الحديد',
    type: 'Medinan',
    verseCount: 29,
    translation: 'The Iron',
    transliteration: 'Al-Hadid',
  },
  {
    id: 58,
    name: 'المجادلة',
    type: 'Medinan',
    verseCount: 22,
    translation: 'The Pleading Woman',
    transliteration: 'Al-Mujadila',
  },
  {
    id: 59,
    name: 'الحشر',
    type: 'Medinan',
    verseCount: 24,
    translation: 'The Exile',
    transliteration: 'Al-Hashr',
  },
  {
    id: 60,
    name: 'الممتحنة',
    type: 'Medinan',
    verseCount: 13,
    translation: 'She that is to be examined',
    transliteration: 'Al-Mumtahanah',
  },
  {
    id: 61,
    name: 'الصف',
    type: 'Medinan',
    verseCount: 14,
    translation: 'The Ranks',
    transliteration: 'As-Saf',
  },
  {
    id: 62,
    name: 'الجمعة',
    type: 'Medinan',
    verseCount: 11,
    translation: 'The Congregation, Friday',
    transliteration: "Al-Jumu'ah",
  },
  {
    id: 63,
    name: 'المنافقون',
    type: 'Medinan',
    verseCount: 11,
    translation: 'The Hypocrites',
    transliteration: 'Al-Munafiqun',
  },
  {
    id: 64,
    name: 'التغابن',
    type: 'Medinan',
    verseCount: 18,
    translation: 'The Mutual Disillusion',
    transliteration: 'At-Taghabun',
  },
  {
    id: 65,
    name: 'الطلاق',
    type: 'Medinan',
    verseCount: 12,
    translation: 'The Divorce',
    transliteration: 'At-Talaq',
  },
  {
    id: 66,
    name: 'التحريم',
    type: 'Medinan',
    verseCount: 12,
    translation: 'The Prohibition',
    transliteration: 'At-Tahrim',
  },
  {
    id: 67,
    name: 'الملك',
    type: 'Meccan',
    verseCount: 30,
    translation: 'The Sovereignty',
    transliteration: 'Al-Mulk',
  },
  {
    id: 68,
    name: 'القلم',
    type: 'Meccan',
    verseCount: 52,
    translation: 'The Pen',
    transliteration: 'Al-Qalam',
  },
  {
    id: 69,
    name: 'الحاقة',
    type: 'Meccan',
    verseCount: 52,
    translation: 'The Reality',
    transliteration: 'Al-Haqqah',
  },
  {
    id: 70,
    name: 'المعارج',
    type: 'Meccan',
    verseCount: 44,
    translation: 'The Ascending Stairways',
    transliteration: "Al-Ma'arij",
  },
  {
    id: 71,
    name: 'نوح',
    type: 'Meccan',
    verseCount: 28,
    translation: 'Noah',
    transliteration: 'Nuh',
  },
  {
    id: 72,
    name: 'الجن',
    type: 'Meccan',
    verseCount: 28,
    translation: 'The Jinn',
    transliteration: 'Al-Jinn',
  },
  {
    id: 73,
    name: 'المزمل',
    type: 'Meccan',
    verseCount: 20,
    translation: 'The Enshrouded One',
    transliteration: 'Al-Muzzammil',
  },
  {
    id: 74,
    name: 'المدثر',
    type: 'Meccan',
    verseCount: 56,
    translation: 'The Cloaked One',
    transliteration: 'Al-Muddaththir',
  },
  {
    id: 75,
    name: 'القيامة',
    type: 'Meccan',
    verseCount: 40,
    translation: 'The Resurrection',
    transliteration: 'Al-Qiyamah',
  },
  {
    id: 76,
    name: 'الانسان',
    type: 'Medinan',
    verseCount: 31,
    translation: 'The Man',
    transliteration: 'Al-Insan',
  },
  {
    id: 77,
    name: 'المرسلات',
    type: 'Meccan',
    verseCount: 50,
    translation: 'The Emissaries',
    transliteration: 'Al-Mursalat',
  },
  {
    id: 78,
    name: 'النبإ',
    type: 'Meccan',
    verseCount: 40,
    translation: 'The Tidings',
    transliteration: 'An-Naba',
  },
  {
    id: 79,
    name: 'النازعات',
    type: 'Meccan',
    verseCount: 46,
    translation: 'Those who drag forth',
    transliteration: "An-Nazi'at",
  },
  {
    id: 80,
    name: 'عبس',
    type: 'Meccan',
    verseCount: 42,
    translation: 'He Frowned',
    transliteration: "'Abasa",
  },
  {
    id: 81,
    name: 'التكوير',
    type: 'Meccan',
    verseCount: 29,
    translation: 'The Overthrowing',
    transliteration: 'At-Takwir',
  },
  {
    id: 82,
    name: 'الإنفطار',
    type: 'Meccan',
    verseCount: 19,
    translation: 'The Cleaving',
    transliteration: 'Al-Infitar',
  },
  {
    id: 83,
    name: 'المطففين',
    type: 'Meccan',
    verseCount: 36,
    translation: 'The Defrauding',
    transliteration: 'Al-Mutaffifin',
  },
  {
    id: 84,
    name: 'الإنشقاق',
    type: 'Meccan',
    verseCount: 25,
    translation: 'The Sundering',
    transliteration: 'Al-Inshiqaq',
  },
  {
    id: 85,
    name: 'البروج',
    type: 'Meccan',
    verseCount: 22,
    translation: 'The Mansions of the Stars',
    transliteration: 'Al-Buruj',
  },
  {
    id: 86,
    name: 'الطارق',
    type: 'Meccan',
    verseCount: 17,
    translation: 'The Nightcommer',
    transliteration: 'At-Tariq',
  },
  {
    id: 87,
    name: 'الأعلى',
    type: 'Meccan',
    verseCount: 19,
    translation: 'The Most High',
    transliteration: "Al-A'la",
  },
  {
    id: 88,
    name: 'الغاشية',
    type: 'Meccan',
    verseCount: 26,
    translation: 'The Overwhelming',
    transliteration: 'Al-Ghashiyah',
  },
  {
    id: 89,
    name: 'الفجر',
    type: 'Meccan',
    verseCount: 30,
    translation: 'The Dawn',
    transliteration: 'Al-Fajr',
  },
  {
    id: 90,
    name: 'البلد',
    type: 'Meccan',
    verseCount: 20,
    translation: 'The City',
    transliteration: 'Al-Balad',
  },
  {
    id: 91,
    name: 'الشمس',
    type: 'Meccan',
    verseCount: 15,
    translation: 'The Sun',
    transliteration: 'Ash-Shams',
  },
  {
    id: 92,
    name: 'الليل',
    type: 'Meccan',
    verseCount: 21,
    translation: 'The Night',
    transliteration: 'Al-Layl',
  },
  {
    id: 93,
    name: 'الضحى',
    type: 'Meccan',
    verseCount: 11,
    translation: 'The Morning Hours',
    transliteration: 'Ad-Duhaa',
  },
  {
    id: 94,
    name: 'الشرح',
    type: 'Meccan',
    verseCount: 8,
    translation: 'The Relief',
    transliteration: 'Ash-Sharh',
  },
  {
    id: 95,
    name: 'التين',
    type: 'Meccan',
    verseCount: 8,
    translation: 'The Fig',
    transliteration: 'At-Tin',
  },
  {
    id: 96,
    name: 'العلق',
    type: 'Meccan',
    verseCount: 19,
    translation: 'The Clot',
    transliteration: "Al-'Alaq",
  },
  {
    id: 97,
    name: 'القدر',
    type: 'Meccan',
    verseCount: 5,
    translation: 'The Power',
    transliteration: 'Al-Qadr',
  },
  {
    id: 98,
    name: 'البينة',
    type: 'Medinan',
    verseCount: 8,
    translation: 'The Clear Proof',
    transliteration: 'Al-Bayyinah',
  },
  {
    id: 99,
    name: 'الزلزلة',
    type: 'Medinan',
    verseCount: 8,
    translation: 'The Earthquake',
    transliteration: 'Az-Zalzalah',
  },
  {
    id: 100,
    name: 'العاديات',
    type: 'Meccan',
    verseCount: 11,
    translation: 'The Courser',
    transliteration: "Al-'Adiyat",
  },
  {
    id: 101,
    name: 'القارعة',
    type: 'Meccan',
    verseCount: 11,
    translation: 'The Calamity',
    transliteration: "Al-Qari'ah",
  },
  {
    id: 102,
    name: 'التكاثر',
    type: 'Meccan',
    verseCount: 8,
    translation: 'The Rivalry in world increase',
    transliteration: 'At-Takathur',
  },
  {
    id: 103,
    name: 'العصر',
    type: 'Meccan',
    verseCount: 3,
    translation: 'The Declining Day',
    transliteration: "Al-'Asr",
  },
  {
    id: 104,
    name: 'الهمزة',
    type: 'Meccan',
    verseCount: 9,
    translation: 'The Traducer',
    transliteration: 'Al-Humazah',
  },
  {
    id: 105,
    name: 'الفيل',
    type: 'Meccan',
    verseCount: 5,
    translation: 'The Elephant',
    transliteration: 'Al-Fil',
  },
  {
    id: 106,
    name: 'قريش',
    type: 'Meccan',
    verseCount: 4,
    translation: 'Quraysh',
    transliteration: 'Quraysh',
  },
  {
    id: 107,
    name: 'الماعون',
    type: 'Meccan',
    verseCount: 7,
    translation: 'The Small kindnesses',
    transliteration: "Al-Ma'un",
  },
  {
    id: 108,
    name: 'الكوثر',
    type: 'Meccan',
    verseCount: 3,
    translation: 'The Abundance',
    transliteration: 'Al-Kawthar',
  },
  {
    id: 109,
    name: 'الكافرون',
    type: 'Meccan',
    verseCount: 6,
    translation: 'The Disbelievers',
    transliteration: 'Al-Kafirun',
  },
  {
    id: 110,
    name: 'النصر',
    type: 'Medinan',
    verseCount: 3,
    translation: 'The Divine Support',
    transliteration: 'An-Nasr',
  },
  {
    id: 111,
    name: 'المسد',
    type: 'Meccan',
    verseCount: 5,
    translation: 'The Palm Fiber',
    transliteration: 'Al-Masad',
  },
  {
    id: 112,
    name: 'الإخلاص',
    type: 'Meccan',
    verseCount: 4,
    translation: 'The Sincerity',
    transliteration: 'Al-Ikhlas',
  },
  {
    id: 113,
    name: 'الفلق',
    type: 'Meccan',
    verseCount: 5,
    translation: 'The Daybreak',
    transliteration: 'Al-Falaq',
  },
  {
    id: 114,
    name: 'الناس',
    type: 'Meccan',
    verseCount: 6,
    translation: 'Mankind',
    transliteration: 'An-Nas',
  },
]
